### PR TITLE
Added different content based on URL

### PR DESCRIPTION
**Pull request by RFX14**
Once running append one of the following to the URL:

* /Josue
* /Calvin
* /Carolina

### CODE REVIEW

**Comment by calvh** [comment]
Thanks @RFX14! 

What do you think about making it a generic page for one person? We could make up a dummy person or base it on one of us. I think that would make it easier to customize later since we don't have to get rid of the extra routes.

**Comment by RFX14** [comment]
So, what you're suggesting is getting rid of the dictionaries I have setup? I'm only confused because the index.html is currently serving as a template for the data in those dictionaries.

**Comment by calvh** [comment]
I suggest  changing `__init__.py` to just contain one person (for example, Miyabi). Since when you're building a portfolio you would only have one person and you won't have multiple routes for different people. 

On the other hand, we could also make this a group portfolio. What are your thoughts?

**Comment by RFX14** [comment]
Ah alright, understand now thanks! I was originally under the impression that we would have each of the group members have a page on this, which would all be following be a template, however I think it's best to discuss this with the entire group to see what direction we should be going.

**Review by calvh — APPROVED** [review]
Closes #4 
Good job

**Pull request merged**
